#!/usr/bin/env python3
"""
Display Graphs from Metrics CSV

This script reads the CSV file generated by gather_metrics.sh and creates
visualizations showing performance metrics across different experiments.

One graph is created per experiment type, with subplots for each metric.
"""

import matplotlib.pyplot as plt
import csv
import sys
import os
import glob
from collections import defaultdict
import argparse


def parse_output_field(output_str):
    """Parse the output field from CSV to extract metrics"""
    metrics = {}
    if output_str == "FAILED":
        return None
    
    # Parse format: "eff=0.107;pred=24.619;fair=283.167"
    parts = output_str.split(';')
    for part in parts:
        if '=' in part:
            key, value = part.split('=')
            try:
                metrics[key] = float(value)
            except ValueError:
                metrics[key] = None
    
    return metrics


def load_csv_data(csv_file):
    """Load and parse the CSV file"""
    data = defaultdict(lambda: defaultdict(list))
    
    with open(csv_file, 'r') as f:
        reader = csv.DictReader(f)
        for row in reader:
            experiment = row['experiment']
            algorithm = row['algorithm']
            
            # Parse metrics from output field
            metrics = parse_output_field(row['output'])
            if metrics is None:
                continue
            
            # Store data point
            data[experiment][algorithm].append({
                'cores': int(row['cores']),
                'jobs': int(row['jobs']),
                'uncertainty': int(row['uncertainty']),
                'avg_length': int(row['avg_length']),
                'avg_threads': int(row['avg_threads']),
                'mutex_prob': float(row.get('mutex_prob', 0.0)),
                'sem_prob': float(row.get('sem_prob', 0.0)),
                'efficiency': metrics.get('eff'),
                'predictability': metrics.get('pred'),
                'fairness': metrics.get('fair')
            })
    
    return data


def sort_data_points(data_points, x_param):
    """Sort data points by the x-axis parameter"""
    return sorted(data_points, key=lambda x: x[x_param])


def plot_experiment(experiment_name, experiment_data, output_dir):
    """Create a figure with subplots for one experiment"""
    
    # Determine x-axis parameter based on experiment name
    x_param_map = {
        'vary_cores': ('cores', 'Number of Cores'),
        'vary_jobs': ('jobs', 'Number of Jobs'),
        'vary_uncertainty': ('uncertainty', 'Uncertainty'),
        'vary_length': ('avg_length', 'Average Job Length'),
        'vary_threads': ('avg_threads', 'Average Thread Count'),
        'vary_mutex': ('mutex_prob', 'Mutex Probability'),
        'vary_semaphore': ('sem_prob', 'Semaphore Probability')
    }
    
    x_param, x_label = x_param_map.get(experiment_name, ('cores', 'Parameter'))
    
    # Create figure with 3 subplots (one per metric)
    fig, axes = plt.subplots(1, 3, figsize=(18, 5))
    fig.suptitle(f'Experiment: {experiment_name.replace("_", " ").title()}', 
                 fontsize=16, fontweight='bold')
    
    # Define metrics to plot
    metrics = [
        ('efficiency', 'Efficiency (Higher is Better)', axes[0]),
        ('predictability', 'Predictability (Lower is Better)', axes[1]),
        ('fairness', 'Fairness (Lower is Better)', axes[2])
    ]
    
    # Colors for each algorithm
    colors = {
        'FIFO': '#1f77b4',
        'PriorityQueue': '#ff7f0e',
        'PCS': '#2ca02c',
        'Preemptive': '#d62728'
    }
    
    # Markers for each algorithm
    markers = {
        'FIFO': 'o',
        'PriorityQueue': 's',
        'PCS': '^',
        'Preemptive': 'D'
    }
    
    # Plot each metric
    for metric_name, metric_title, ax in metrics:
        for algorithm, data_points in sorted(experiment_data.items()):
            # Sort data points by x parameter
            sorted_points = sort_data_points(data_points, x_param)
            
            # Extract x and y values
            x_values = [point[x_param] for point in sorted_points]
            y_values = [point[metric_name] for point in sorted_points 
                       if point[metric_name] is not None]
            
            # Skip if no valid data
            if not y_values or len(y_values) != len(x_values):
                continue
            
            # Plot line with markers
            ax.plot(x_values, y_values, 
                   label=algorithm,
                   marker=markers.get(algorithm, 'o'),
                   color=colors.get(algorithm, 'gray'),
                   linewidth=2,
                   markersize=8,
                   linestyle='-',
                   alpha=0.8)
        
        # Configure subplot
        ax.set_xlabel(x_label, fontsize=12, fontweight='bold')
        ax.set_ylabel(metric_title.split('(')[0].strip(), fontsize=12, fontweight='bold')
        ax.set_title(metric_title, fontsize=11)
        ax.set_yscale('log')
        ax.legend(loc='best', framealpha=0.9)
        ax.grid(True, alpha=0.3, linestyle='--')
        
        # Use integer x-axis if appropriate
        if x_param in ['cores', 'jobs', 'uncertainty', 'avg_length', 'avg_threads']:
            ax.set_xticks([point[x_param] for point in 
                          sort_data_points(list(experiment_data.values())[0], x_param)])
    
    # Adjust layout
    plt.tight_layout()
    
    # Save figure
    output_file = os.path.join(output_dir, f'{experiment_name}.png')
    plt.savefig(output_file, dpi=300, bbox_inches='tight')
    print(f"Saved: {output_file}")
    
    return fig


def create_summary_plot(all_data, output_dir):
    """Create a summary plot comparing all experiments"""
    fig, axes = plt.subplots(3, 3, figsize=(20, 16))
    fig.suptitle('Summary: All Experiments', fontsize=18, fontweight='bold')
    
    experiments = ['vary_cores', 'vary_jobs', 'vary_uncertainty', 
                   'vary_length', 'vary_threads', 'vary_mutex', 'vary_semaphore']
    
    colors = {
        'FIFO': '#1f77b4',
        'PriorityQueue': '#ff7f0e',
        'PCS': '#2ca02c',
        'Preemptive': '#d62728'
    }
    
    for idx, experiment in enumerate(experiments):
        if experiment not in all_data:
            continue
        
        row = idx // 3
        col = idx % 3
        ax = axes[row, col]
        
        # Plot efficiency for this experiment
        experiment_data = all_data[experiment]
        x_param = experiment.replace('vary_', '')
        if x_param == 'threads':
            x_param = 'avg_threads'
        elif x_param == 'length':
            x_param = 'avg_length'
        elif x_param == 'mutex':
            x_param = 'mutex_prob'
        elif x_param == 'semaphore':
            x_param = 'sem_prob'
        
        for algorithm, data_points in sorted(experiment_data.items()):
            sorted_points = sort_data_points(data_points, x_param)
            x_values = [point[x_param] for point in sorted_points]
            y_values = [point['efficiency'] for point in sorted_points 
                       if point['efficiency'] is not None]
            
            if y_values and len(y_values) == len(x_values):
                ax.plot(x_values, y_values, 
                       label=algorithm,
                       marker='o',
                       color=colors.get(algorithm, 'gray'),
                       linewidth=2)
        
        ax.set_title(experiment.replace('_', ' ').title(), fontsize=12, fontweight='bold')
        ax.set_xlabel(x_param.replace('_', ' ').title(), fontsize=10)
        ax.set_ylabel('Efficiency', fontsize=10)
        ax.set_yscale('log')
        ax.legend(loc='best', fontsize=8)
        ax.grid(True, alpha=0.3)
    
    # Remove extra subplots (we have 7 experiments, leaving 2 empty in 3x3 grid)
    fig.delaxes(axes[2, 1])
    fig.delaxes(axes[2, 2])
    
    plt.tight_layout()
    
    output_file = os.path.join(output_dir, 'summary_all_experiments.png')
    plt.savefig(output_file, dpi=300, bbox_inches='tight')
    print(f"Saved: {output_file}")
    
    return fig


def main():
    parser = argparse.ArgumentParser(description='Create visualizations from metrics CSV')
    parser.add_argument('csv_file', nargs='?', help='Path to CSV file (if not provided, uses most recent)')
    parser.add_argument('-o', '--output', default='metrics_output/graphs', 
                       help='Output directory for graphs')
    parser.add_argument('--show', action='store_true', help='Show plots interactively')
    parser.add_argument('--no-summary', action='store_true', help='Skip summary plot')
    
    args = parser.parse_args()
    
    # Find CSV file if not provided
    if args.csv_file is None:
        csv_files = glob.glob('metrics_output/metrics_*.csv')
        if not csv_files:
            print("Error: No CSV files found in metrics_output/")
            print("Run ./gather_metrics.sh first to generate data")
            sys.exit(1)
        
        # Use most recent file
        args.csv_file = max(csv_files, key=os.path.getmtime)
        print(f"Using most recent CSV: {args.csv_file}")
    
    # Check if file exists
    if not os.path.exists(args.csv_file):
        print(f"Error: CSV file not found: {args.csv_file}")
        sys.exit(1)
    
    # Create output directory
    os.makedirs(args.output, exist_ok=True)
    
    # Load data
    print(f"Loading data from {args.csv_file}...")
    data = load_csv_data(args.csv_file)
    
    if not data:
        print("Error: No data found in CSV file")
        sys.exit(1)
    
    print(f"Found {len(data)} experiments")
    
    # Create plots for each experiment
    figures = []
    for experiment_name in sorted(data.keys()):
        print(f"Creating plots for {experiment_name}...")
        fig = plot_experiment(experiment_name, data[experiment_name], args.output)
        figures.append(fig)
    
    # Create summary plot
    if not args.no_summary:
        print("Creating summary plot...")
        summary_fig = create_summary_plot(data, args.output)
        figures.append(summary_fig)
    
    print(f"\nAll graphs saved to {args.output}/")
    
    # Show plots if requested
    if args.show:
        plt.show()
    else:
        plt.close('all')


if __name__ == "__main__":
    main()
